### ISSUE TITLE
[bug] can't make it work with simple use-case.

### ISSUE THREAD

**Issue by z0ph** [BobAnkh/add-contributors#27]
## Describe the bug

Exception: The file where contributors are trying to be written 'README.md' does not have '### Contributors

I've tried with `/README.md` and `README.md`, I've tried with just `### Contributors` section with just blank line just after. Nothing is working.

## To Reproduce

```
name: Add contributors
on:
  schedule:
    - cron:  '20 20 * * *'
  push:
    branches:
      - dev

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: BobAnkh/add-contributors@master
      with:
        REPO_NAME: 'zoph-io/awscon-onepager'
        CONTRIBUTOR: '### Contributors'
        COLUMN_PER_ROW: '6'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '60'
        FONT_SIZE: '10'
        PATH: 'README.md'
        COMMIT_MESSAGE: 'docs(README): update contributors'
        AVATAR_SHAPE: 'round'
```

## Expected behavior

Update contributors in `README.md`

## Screenshots

![image](https://user-images.githubusercontent.com/20846187/100143095-1444f380-2e95-11eb-8f82-293ba303d273.png)
